import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:rentora/core/services/fcm_service.dart';
import 'package:rentora/features/properties/presentation/providers/favorites_providers.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:toastification/toastification.dart';

import 'core/router/app_router.dart';
import 'core/theme/app_theme.dart';
import 'firebase_options.dart'; // generated by: flutterfire configure

/// Must be a top-level function — Flutter runs this in an isolate when the
/// app is terminated or in the background.
@pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  // Firebase must be re-initialised inside background isolates.
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // The system tray notification is shown automatically by FCM when the app is
  // in background/terminated — no extra work needed here unless you want custom
  // handling (e.g. writing to a local DB).
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ── Firebase ─────────────────────────────────────────────────────────────
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

  // Foreground FCM listener.
  FcmService().setupForegroundHandler();

  // Lock to portrait — rental browsing app doesn't need landscape.
  SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown,
  ]);

  // Edge-to-edge: transparent status + nav bars.
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.dark,
      systemNavigationBarColor: Colors.transparent,
      systemNavigationBarIconBrightness: Brightness.dark,
    ),
  );

  // ── Initialize SharedPreferences here ────────────────────────────────────
  final prefs = await SharedPreferences.getInstance();

  runApp(
    // Inject the initialized instance into the ProviderScope
    ProviderScope(
      overrides: [sharedPreferencesProvider.overrideWithValue(prefs)],
      child: const RentoraApp(),
    ),
  );
}

class RentoraApp extends StatelessWidget {
  const RentoraApp({super.key});

  @override
  Widget build(BuildContext context) {
    return ToastificationWrapper(
      child: MaterialApp.router(
        title: 'Rentora',
        debugShowCheckedModeBanner: false,

        // Theme
        theme: AppTheme.light,

        // Navigation
        routerConfig: appRouter,
      ),
    );
  }
}
